export const UPDATE_IS_OPEN_MODAL = 'UPDATE_IS_OPEN_MODAL';
export const UPDATE_IS_ACTIVED_DESTINATION = 'UPDATE_IS_ACTIVED_DESTINATION';
export const ADD_DESTINATION = 'ADD_DESTINATION';
export const SET_DESTINATION = 'SET_DESTINATION';
